stages:
  - build
  - test
  - publish
  - spatest
  - imagebuild

build:
  stage: build
  script:
    - ./build.sh -target=Build
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - ./build.sh -target=UnitTests
  dependencies:
    - build

publish:
  stage: publish
  script:
    - ./build.sh -target=Publish
  dependencies:
    - test:dotnet
    - test:spa
  artifacts:
    untracked: true
    paths:
      - publish/

spatest:
  stage: spatest
  script:
    - ./build.sh -target=SPATests
  dependencies:
    - publish

imagebuild:
  stage: imagebuild
  script:
    - ./build.sh -target=ImageBuild
  dependencies:
    - publish