stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - ./build.sh -target=Build

test:
  stage: test
  script:
    - ./build.sh -target=UnitTests -verbosity=diagnostic
  dependencies:
    - build

publish:
  stage: publish
  script:
    - ./build.sh -target=Publish
  dependencies:
    - test
  artifacts:
    paths:
      - publish/
