stages:
  - build
  - test
  - publish
  - spatest
  - imagebuild

build:
  stage: build
  script:
    - ./build.sh -target=Build
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - ./build.sh -target=UnitTests

publish:
  stage: publish
  script:
    - ./build.sh -target=Publish
  artifacts:
    untracked: true
    paths:
      - publish/

spatest:
  stage: spatest
  script:
    - ./build.sh -target=SPATests

imagebuild:
  stage: imagebuild
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.cdpoc
    - ./build.sh -target=ImageBuild