version: '3'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

