version: '2'

services:
  webapi:
    image: registry.cdpoc/arcmedia/dialogweaver/webapi
    ports:
      - "5000:80"

  webspa:
    image: registry.cdpoc/arcmedia/dialogweaver/webspa
    depends_on:
      - webapi
    ports:
      - "5001:80"
